{
    'name': 'Smart Dashboard',
    'version': '18.0',
    'category': 'Productivity',
    'summery': 'Smart Dashboard',
    'author': '',
    'depends': ['base', 'web'],
    'data': [
        'security/custom_dashboard_security.xml',
        'security/ir.model.access.csv',
        'views/eg_custom_dashboard_item_view.xml',
        'views/custom_dashboard_board.xml',
        'data/custom_dashboard_client_actions.xml',
    ],
    'demo': [
        'demo/dashboard_charts_demo.xml',
    ],
    'assets': {
        'web.assets_common': [
        ],

        'web.assets_backend': [
            'eg_ai_smart_dashboard_lite/static/lib/jquery/jquery.js',
            'eg_ai_smart_dashboard_lite/static/lib/js/jquery.ui.mi.js',
            'eg_ai_smart_dashboard_lite/static/lib/js/lodash.min.js',
            'eg_ai_smart_dashboard_lite/static/lib/js/gridstack.min.js',
            'eg_ai_smart_dashboard_lite/static/lib/js/gridstack.jQueryUI.min.js',

            'eg_ai_smart_dashboard_lite/static/src/xml/ColorPickerWidget.xml',
            'eg_ai_smart_dashboard_lite/static/src/xml/DashboardIconPicker.xml',
            'eg_ai_smart_dashboard_lite/static/src/xml/DashboardTilePreview.xml',
            'eg_ai_smart_dashboard_lite/static/src/xml/DashboardTile.xml',
            'eg_ai_smart_dashboard_lite/static/src/xml/CustomChartListViewPreview.xml',
            'eg_ai_smart_dashboard_lite/static/src/xml/CustomChartListView.xml',
            'eg_ai_smart_dashboard_lite/static/src/xml/ChartUpdateButton.xml',
            'eg_ai_smart_dashboard_lite/static/src/xml/custom_dashboard_qweb.xml',
            'eg_ai_smart_dashboard_lite/static/src/js/ColorPickerWidget.js',
            'eg_ai_smart_dashboard_lite/static/src/js/DashboardIconPicker.js',
            'eg_ai_smart_dashboard_lite/static/src/js/chart_update_button.js',
            'eg_ai_smart_dashboard_lite/static/src/js/dashboard_board.js',
            'eg_ai_smart_dashboard_lite/static/src/xml/custom_dashboard_view.xml',
            'eg_ai_smart_dashboard_lite/static/src/xml/CustomDashboardBoard.xml',
            'eg_ai_smart_dashboard_lite/static/src/xml/KpiTile.xml',
            'eg_ai_smart_dashboard_lite/static/src/css/dashboard_item_kanban.css',
            'eg_ai_smart_dashboard_lite/static/src/css/custom_dashboard.css',
            'eg_ai_smart_dashboard_lite/static/lib/js/spectrum.js',
            'eg_ai_smart_dashboard_lite/static/lib/js/echart.js',
            'eg_ai_smart_dashboard_lite/static/lib/js/theme.js',
            'eg_ai_smart_dashboard_lite/static/lib/js/bootstrap-iconpicker.min.js',

            'eg_ai_smart_dashboard_lite/static/lib/js/css/spectrum.css',
            'eg_ai_smart_dashboard_lite/static/lib/js/css/bootstrap-iconpicker.min.css',
            'eg_ai_smart_dashboard_lite/static/lib/js/css/gridstack.min.css',
            'eg_ai_smart_dashboard_lite/static/lib/js/css/spectrum.css',
            'eg_ai_smart_dashboard_lite/static/src/js/form_view.js',
            'eg_ai_smart_dashboard_lite/static/lib/js/sweetalert.min.js',
            'eg_ai_smart_dashboard_lite/static/lib/js/css/sweetalert.css',
        ],
    },
    'images': ['static/description/banner.png'],
    'license': "OPL-1",
    'installable': True,
    'application': True,
    'auto_install': False,
}
